m

diff --git a/bin/dd-burn b/bin/dd-burn
--- a/bin/dd-burn
+++ b/bin/dd-burn
@@ -1,28 +1,25 @@
 #!/bin/sh -e
-#L:
 #L:  MIT License
-#L:  
-#l:  Bug reports, feature requests to gemini|https://harkadev.com/oss
+#L:
 #l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
 #L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining
-#L:  a copy of this software and associated documentation files (the
-#L:  "Software"), to deal in the Software without restriction, including
-#L:  without limitation the rights to use, copy, modify, merge, publish,
-#L:  distribute, sublicense, and/or sell copies of the Software, and to
-#L:  permit persons to whom the Software is furnished to do so, subject to
-#L:  the following conditions:
+#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
+#L:  of this software and associated documentation files (the "Software"), to deal
+#L:  in the Software without restriction, including without limitation the rights
+#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+#L:  copies of the Software, and to permit persons to whom the Software is
+#L:  furnished to do so, subject to the following conditions:
 #L:
-#L:  The above copyright notice and this permission notice shall be
-#L:  included in all copies or substantial portions of the Software.
+#L:  The above copyright notice and this permission notice shall be included in all
+#L:  copies or substantial portions of the Software.
 #L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
-#L:  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-#L:  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
-#L:  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
-#L:  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
-#L:  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
-#L:  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+#L:  SOFTWARE.
 ##:
 #h: Usage: $0 IMG[.xz] DEV
 #h:
@@ -30,7 +27,6 @@
 ##:
 #D: xzcat, zcat, GNUdd
 ##:
-. ask-block-device
 dd_burn() (
     img="$1" dev="`ask_block_device "$2"`" progs="sudo dd" type="" p=""
     if test ! -n "$dev"; then
@@ -62,6 +58,17 @@ dd_burn() (
     echo "Sync"
     sync
 )
+ask_block_device() {
+    if test ! -n "$1"; then
+        echo "error: Please specify a block device." >&2
+        return 1
+    elif test ! -b "$1"; then
+        echo "error: $1: Not a block device." >&2
+        return 1
+    else
+        echo "$1"
+    fi
+}
 SCRNAME="`basename "$0"`"
 if test @"${SCRNAME}" = @"dd-burn";then
     case "${1}" in
