m

diff --git a/bin/liso b/bin/liso
--- a/bin/liso
+++ b/bin/liso
@@ -1,27 +1,6 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
 ##:
-#h: Usage: $0 [-m] ISO DRIVE
+#h: Usage: liso [-m] ISO DRIVE
 #h:
 #h: This program first formats the DRIVE to FAT32 and then
 #h: extracts a GNU/Linux installation iso image to it. This
@@ -113,18 +92,12 @@ liso() {
     liso_info "Syncing ..."
     sync
 }
-## -----------------------------------------------------------------------------
-
-## -----------------------------------------------------------------------------
-liso_info()  { echo "${SCRNAME}: $*";            }
-liso_error() { echo "${SCRNAME}: error: $*" >&2; }
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"liso";then
-    if test -n "$1";then
-        liso "$@"
-    else
-        sed -n 's/^ *#h: \{0,1\}//p' "$0" | sed "s|\\\$0|`basename $0`|g"
-        echo ""
-        sed -n 's/^ *#l: \{0,2\}//p' "$0"
-    fi
+## -------------------------------------------------------------------
+liso_info()  { echo "$*";            }
+liso_error() { echo "error: $*" >&2; }
+if test @"$(basename "$0")" = @"liso"; then
+    case "${1}" in
+        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
+        *)            liso "$@"; exit 0;;
+    esac
 fi
